// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet/greetpb/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyTimesRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesRequest) Reset()         { *m = GreetManyTimesRequest{} }
func (m *GreetManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesRequest) ProtoMessage()    {}
func (*GreetManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{3}
}

func (m *GreetManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesRequest.Unmarshal(m, b)
}
func (m *GreetManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesRequest.Merge(m, src)
}
func (m *GreetManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesRequest.Size(m)
}
func (m *GreetManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesRequest proto.InternalMessageInfo

func (m *GreetManyTimesRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type GreetManyTimesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesResponse) Reset()         { *m = GreetManyTimesResponse{} }
func (m *GreetManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesResponse) ProtoMessage()    {}
func (*GreetManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{4}
}

func (m *GreetManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesResponse.Unmarshal(m, b)
}
func (m *GreetManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesResponse.Merge(m, src)
}
func (m *GreetManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesResponse.Size(m)
}
func (m *GreetManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesResponse proto.InternalMessageInfo

func (m *GreetManyTimesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LongGreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LongGreetRequest) Reset()         { *m = LongGreetRequest{} }
func (m *LongGreetRequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetRequest) ProtoMessage()    {}
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{5}
}

func (m *LongGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetRequest.Unmarshal(m, b)
}
func (m *LongGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetRequest.Marshal(b, m, deterministic)
}
func (m *LongGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetRequest.Merge(m, src)
}
func (m *LongGreetRequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetRequest.Size(m)
}
func (m *LongGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetRequest proto.InternalMessageInfo

func (m *LongGreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type LongGreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetResponse) Reset()         { *m = LongGreetResponse{} }
func (m *LongGreetResponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetResponse) ProtoMessage()    {}
func (*LongGreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{6}
}

func (m *LongGreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetResponse.Unmarshal(m, b)
}
func (m *LongGreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetResponse.Marshal(b, m, deterministic)
}
func (m *LongGreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetResponse.Merge(m, src)
}
func (m *LongGreetResponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetResponse.Size(m)
}
func (m *LongGreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetResponse proto.InternalMessageInfo

func (m *LongGreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetEveryOneRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryOneRequest) Reset()         { *m = GreetEveryOneRequest{} }
func (m *GreetEveryOneRequest) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneRequest) ProtoMessage()    {}
func (*GreetEveryOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{7}
}

func (m *GreetEveryOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneRequest.Unmarshal(m, b)
}
func (m *GreetEveryOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneRequest.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneRequest.Merge(m, src)
}
func (m *GreetEveryOneRequest) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneRequest.Size(m)
}
func (m *GreetEveryOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneRequest proto.InternalMessageInfo

func (m *GreetEveryOneRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type GreetEveryOneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryOneResponse) Reset()         { *m = GreetEveryOneResponse{} }
func (m *GreetEveryOneResponse) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneResponse) ProtoMessage()    {}
func (*GreetEveryOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{8}
}

func (m *GreetEveryOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneResponse.Unmarshal(m, b)
}
func (m *GreetEveryOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneResponse.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneResponse.Merge(m, src)
}
func (m *GreetEveryOneResponse) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneResponse.Size(m)
}
func (m *GreetEveryOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneResponse proto.InternalMessageInfo

func (m *GreetEveryOneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetWithDeadLineRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetWithDeadLineRequest) Reset()         { *m = GreetWithDeadLineRequest{} }
func (m *GreetWithDeadLineRequest) String() string { return proto.CompactTextString(m) }
func (*GreetWithDeadLineRequest) ProtoMessage()    {}
func (*GreetWithDeadLineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{9}
}

func (m *GreetWithDeadLineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetWithDeadLineRequest.Unmarshal(m, b)
}
func (m *GreetWithDeadLineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetWithDeadLineRequest.Marshal(b, m, deterministic)
}
func (m *GreetWithDeadLineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetWithDeadLineRequest.Merge(m, src)
}
func (m *GreetWithDeadLineRequest) XXX_Size() int {
	return xxx_messageInfo_GreetWithDeadLineRequest.Size(m)
}
func (m *GreetWithDeadLineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetWithDeadLineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetWithDeadLineRequest proto.InternalMessageInfo

func (m *GreetWithDeadLineRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type GreetWithDeadLineResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetWithDeadLineResponse) Reset()         { *m = GreetWithDeadLineResponse{} }
func (m *GreetWithDeadLineResponse) String() string { return proto.CompactTextString(m) }
func (*GreetWithDeadLineResponse) ProtoMessage()    {}
func (*GreetWithDeadLineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{10}
}

func (m *GreetWithDeadLineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetWithDeadLineResponse.Unmarshal(m, b)
}
func (m *GreetWithDeadLineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetWithDeadLineResponse.Marshal(b, m, deterministic)
}
func (m *GreetWithDeadLineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetWithDeadLineResponse.Merge(m, src)
}
func (m *GreetWithDeadLineResponse) XXX_Size() int {
	return xxx_messageInfo_GreetWithDeadLineResponse.Size(m)
}
func (m *GreetWithDeadLineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetWithDeadLineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetWithDeadLineResponse proto.InternalMessageInfo

func (m *GreetWithDeadLineResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greetpb.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greetpb.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greetpb.GreetResponse")
	proto.RegisterType((*GreetManyTimesRequest)(nil), "greetpb.GreetManyTimesRequest")
	proto.RegisterType((*GreetManyTimesResponse)(nil), "greetpb.GreetManyTimesResponse")
	proto.RegisterType((*LongGreetRequest)(nil), "greetpb.LongGreetRequest")
	proto.RegisterType((*LongGreetResponse)(nil), "greetpb.LongGreetResponse")
	proto.RegisterType((*GreetEveryOneRequest)(nil), "greetpb.GreetEveryOneRequest")
	proto.RegisterType((*GreetEveryOneResponse)(nil), "greetpb.GreetEveryOneResponse")
	proto.RegisterType((*GreetWithDeadLineRequest)(nil), "greetpb.GreetWithDeadLineRequest")
	proto.RegisterType((*GreetWithDeadLineResponse)(nil), "greetpb.GreetWithDeadLineResponse")
}

func init() { proto.RegisterFile("greet/greetpb/greet.proto", fileDescriptor_fe6f881da19a2871) }

var fileDescriptor_fe6f881da19a2871 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x4b, 0x02, 0x41,
	0x10, 0xc7, 0xbb, 0x22, 0xf3, 0xa6, 0x1f, 0xe4, 0x90, 0xa2, 0x1b, 0x5a, 0xdd, 0x4b, 0x42, 0xa4,
	0xa2, 0x10, 0xbd, 0xf4, 0x50, 0x94, 0xbd, 0x58, 0x81, 0x19, 0x41, 0x04, 0x71, 0xd6, 0x74, 0x1d,
	0xe8, 0x9d, 0xdd, 0xad, 0x82, 0x7f, 0x4b, 0xff, 0x6c, 0xb8, 0xee, 0xaa, 0xb7, 0xf9, 0x0b, 0x7a,
	0xd1, 0xdb, 0x99, 0xf9, 0x7e, 0x3f, 0xbb, 0x3b, 0xc3, 0x42, 0xc6, 0x09, 0x88, 0x78, 0x51, 0xfc,
	0x76, 0x9a, 0xc3, 0xff, 0x42, 0x27, 0xf0, 0xb9, 0x8f, 0x1b, 0x32, 0x68, 0x55, 0x21, 0x7e, 0x3b,
	0xf8, 0x74, 0x3d, 0x07, 0xb3, 0x00, 0x9f, 0x6e, 0x10, 0xf2, 0x37, 0xcf, 0x6e, 0x53, 0xda, 0x38,
	0x34, 0xf2, 0x66, 0xdd, 0x14, 0x91, 0x7b, 0xbb, 0x4d, 0xb8, 0x0f, 0x66, 0xcb, 0x56, 0xd9, 0x55,
	0x91, 0x8d, 0x0f, 0x02, 0x83, 0xa4, 0x75, 0x01, 0x5b, 0xc2, 0xa7, 0x4e, 0xdf, 0x5d, 0x0a, 0x39,
	0x9e, 0x42, 0xdc, 0x91, 0xbe, 0xc2, 0x69, 0xb3, 0x9c, 0x28, 0x48, 0x66, 0x41, 0x01, 0xeb, 0xa3,
	0x12, 0xeb, 0x18, 0xb6, 0xa5, 0x3c, 0xec, 0xf8, 0x5e, 0x48, 0x98, 0x82, 0x58, 0x40, 0x61, 0xb7,
	0xc5, 0xe5, 0x3e, 0xe4, 0xca, 0xaa, 0x40, 0x52, 0x14, 0xde, 0xd9, 0x5e, 0xbf, 0xe1, 0xb6, 0x29,
	0x54, 0x40, 0xa6, 0x01, 0xcd, 0x09, 0xf7, 0x12, 0xa4, 0x74, 0xd1, 0x02, 0xcc, 0x25, 0xec, 0xd6,
	0x7c, 0xcf, 0xf9, 0xcf, 0x91, 0x4e, 0x20, 0x31, 0x61, 0xb1, 0x80, 0x57, 0x86, 0x3d, 0x51, 0x78,
	0xd3, 0xa3, 0xa0, 0xff, 0xe0, 0xd1, 0x32, 0xa7, 0x2a, 0xca, 0xab, 0x18, 0x6b, 0x16, 0x40, 0xce,
	0x20, 0x2d, 0x04, 0xcf, 0x2e, 0xff, 0xba, 0x26, 0xfb, 0xa3, 0xe6, 0x2e, 0x07, 0xaa, 0x40, 0x66,
	0x8a, 0x6e, 0x3e, 0xac, 0xfc, 0xb3, 0x26, 0x27, 0xe2, 0x91, 0x82, 0x9e, 0xfb, 0x4e, 0x78, 0x0e,
	0xeb, 0x62, 0x8d, 0xc9, 0xe8, 0xad, 0xc9, 0x1d, 0xb0, 0x94, 0x1e, 0x1e, 0x02, 0xac, 0x15, 0x7c,
	0x82, 0x9d, 0x68, 0xfb, 0x30, 0x17, 0xad, 0xd5, 0x87, 0x81, 0x1d, 0xcc, 0xcc, 0x2b, 0xd3, 0x92,
	0x81, 0x55, 0x30, 0x47, 0x0d, 0xc2, 0xcc, 0x48, 0xa1, 0xf7, 0x9d, 0xb1, 0x69, 0x29, 0xe5, 0x93,
	0x37, 0xb0, 0x21, 0x67, 0x57, 0xf5, 0x01, 0xb3, 0x51, 0xba, 0xd6, 0x53, 0x96, 0x9b, 0x95, 0x1e,
	0x7b, 0x96, 0x0c, 0x7c, 0x85, 0xc4, 0x9f, 0x4b, 0xc7, 0xa3, 0xa8, 0x74, 0x4a, 0x23, 0x99, 0x35,
	0xaf, 0x44, 0x11, 0xae, 0xcc, 0x17, 0xf5, 0x02, 0x34, 0x63, 0xe2, 0x45, 0xa8, 0xfc, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x8a, 0x8f, 0x18, 0x2e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	// Unary
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	// Server Streaming
	GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error)
	// Client Streaming
	LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error)
	// Bi Di Streaming
	GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error)
	// Unary deadline
	GreetWithDeadLine(ctx context.Context, in *GreetWithDeadLineRequest, opts ...grpc.CallOption) (*GreetWithDeadLineResponse, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greetpb.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greetpb.GreetService/GreetManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetManyTimesClient interface {
	Recv() (*GreetManyTimesResponse, error)
	grpc.ClientStream
}

type greetServiceGreetManyTimesClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetManyTimesClient) Recv() (*GreetManyTimesResponse, error) {
	m := new(GreetManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greetpb.GreetService/LongGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceLongGreetClient{stream}
	return x, nil
}

type GreetService_LongGreetClient interface {
	Send(*LongGreetRequest) error
	CloseAndRecv() (*LongGreetResponse, error)
	grpc.ClientStream
}

type greetServiceLongGreetClient struct {
	grpc.ClientStream
}

func (x *greetServiceLongGreetClient) Send(m *LongGreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceLongGreetClient) CloseAndRecv() (*LongGreetResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongGreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/greetpb.GreetService/GreetEveryOne", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetEveryOneClient{stream}
	return x, nil
}

type GreetService_GreetEveryOneClient interface {
	Send(*GreetEveryOneRequest) error
	Recv() (*GreetEveryOneResponse, error)
	grpc.ClientStream
}

type greetServiceGreetEveryOneClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetEveryOneClient) Send(m *GreetEveryOneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneClient) Recv() (*GreetEveryOneResponse, error) {
	m := new(GreetEveryOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetWithDeadLine(ctx context.Context, in *GreetWithDeadLineRequest, opts ...grpc.CallOption) (*GreetWithDeadLineResponse, error) {
	out := new(GreetWithDeadLineResponse)
	err := c.cc.Invoke(ctx, "/greetpb.GreetService/GreetWithDeadLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	// Unary
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	// Server Streaming
	GreetManyTimes(*GreetManyTimesRequest, GreetService_GreetManyTimesServer) error
	// Client Streaming
	LongGreet(GreetService_LongGreetServer) error
	// Bi Di Streaming
	GreetEveryOne(GreetService_GreetEveryOneServer) error
	// Unary deadline
	GreetWithDeadLine(context.Context, *GreetWithDeadLineRequest) (*GreetWithDeadLineResponse, error)
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetManyTimes(req *GreetManyTimesRequest, srv GreetService_GreetManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetManyTimes not implemented")
}
func (*UnimplementedGreetServiceServer) LongGreet(srv GreetService_LongGreetServer) error {
	return status.Errorf(codes.Unimplemented, "method LongGreet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetEveryOne(srv GreetService_GreetEveryOneServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetEveryOne not implemented")
}
func (*UnimplementedGreetServiceServer) GreetWithDeadLine(ctx context.Context, req *GreetWithDeadLineRequest) (*GreetWithDeadLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetWithDeadLine not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetpb.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetManyTimes(m, &greetServiceGreetManyTimesServer{stream})
}

type GreetService_GreetManyTimesServer interface {
	Send(*GreetManyTimesResponse) error
	grpc.ServerStream
}

type greetServiceGreetManyTimesServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetManyTimesServer) Send(m *GreetManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_LongGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).LongGreet(&greetServiceLongGreetServer{stream})
}

type GreetService_LongGreetServer interface {
	SendAndClose(*LongGreetResponse) error
	Recv() (*LongGreetRequest, error)
	grpc.ServerStream
}

type greetServiceLongGreetServer struct {
	grpc.ServerStream
}

func (x *greetServiceLongGreetServer) SendAndClose(m *LongGreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceLongGreetServer) Recv() (*LongGreetRequest, error) {
	m := new(LongGreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetEveryOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetEveryOne(&greetServiceGreetEveryOneServer{stream})
}

type GreetService_GreetEveryOneServer interface {
	Send(*GreetEveryOneResponse) error
	Recv() (*GreetEveryOneRequest, error)
	grpc.ServerStream
}

type greetServiceGreetEveryOneServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetEveryOneServer) Send(m *GreetEveryOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneServer) Recv() (*GreetEveryOneRequest, error) {
	m := new(GreetEveryOneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetWithDeadLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetWithDeadLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GreetWithDeadLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetpb.GreetService/GreetWithDeadLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GreetWithDeadLine(ctx, req.(*GreetWithDeadLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetpb.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
		{
			MethodName: "GreetWithDeadLine",
			Handler:    _GreetService_GreetWithDeadLine_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTimes",
			Handler:       _GreetService_GreetManyTimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongGreet",
			Handler:       _GreetService_LongGreet_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GreetEveryOne",
			Handler:       _GreetService_GreetEveryOne_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greet/greetpb/greet.proto",
}
