// Code generated by protoc-gen-go. DO NOT EDIT.
// source: findmax/findmax/findmax.proto

package findmax

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindMaxRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxRequest) Reset()         { *m = FindMaxRequest{} }
func (m *FindMaxRequest) String() string { return proto.CompactTextString(m) }
func (*FindMaxRequest) ProtoMessage()    {}
func (*FindMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1aa76014bc753fa, []int{0}
}

func (m *FindMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxRequest.Unmarshal(m, b)
}
func (m *FindMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxRequest.Marshal(b, m, deterministic)
}
func (m *FindMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxRequest.Merge(m, src)
}
func (m *FindMaxRequest) XXX_Size() int {
	return xxx_messageInfo_FindMaxRequest.Size(m)
}
func (m *FindMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxRequest proto.InternalMessageInfo

func (m *FindMaxRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FindMaxResponse struct {
	MaximumNumber        int64    `protobuf:"varint,1,opt,name=maximumNumber,proto3" json:"maximumNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxResponse) Reset()         { *m = FindMaxResponse{} }
func (m *FindMaxResponse) String() string { return proto.CompactTextString(m) }
func (*FindMaxResponse) ProtoMessage()    {}
func (*FindMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1aa76014bc753fa, []int{1}
}

func (m *FindMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxResponse.Unmarshal(m, b)
}
func (m *FindMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxResponse.Marshal(b, m, deterministic)
}
func (m *FindMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxResponse.Merge(m, src)
}
func (m *FindMaxResponse) XXX_Size() int {
	return xxx_messageInfo_FindMaxResponse.Size(m)
}
func (m *FindMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxResponse proto.InternalMessageInfo

func (m *FindMaxResponse) GetMaximumNumber() int64 {
	if m != nil {
		return m.MaximumNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*FindMaxRequest)(nil), "findmax.FindMaxRequest")
	proto.RegisterType((*FindMaxResponse)(nil), "findmax.FindMaxResponse")
}

func init() { proto.RegisterFile("findmax/findmax/findmax.proto", fileDescriptor_c1aa76014bc753fa) }

var fileDescriptor_c1aa76014bc753fa = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0xcb, 0xcc, 0x4b,
	0xc9, 0x4d, 0xac, 0xd0, 0x47, 0xa3, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8, 0xa1, 0x5c,
	0x25, 0x0d, 0x2e, 0x3e, 0xb7, 0xcc, 0xbc, 0x14, 0xdf, 0xc4, 0x8a, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xbc, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0x28, 0x4f, 0xc9, 0x9c, 0x8b, 0x1f, 0xae, 0xb2, 0xb8, 0x20, 0x3f, 0xaf, 0x38,
	0x55, 0x48, 0x85, 0x8b, 0x37, 0x37, 0xb1, 0x22, 0x33, 0xb7, 0x34, 0xd7, 0x0f, 0x59, 0x07, 0xaa,
	0xa0, 0x91, 0x2f, 0x17, 0x3b, 0x54, 0xa3, 0x90, 0x13, 0x82, 0x29, 0xae, 0x07, 0x73, 0x11, 0xaa,
	0xfd, 0x52, 0x12, 0x98, 0x12, 0x10, 0xeb, 0x94, 0x18, 0x34, 0x18, 0x0d, 0x18, 0x9d, 0x38, 0xa3,
	0x60, 0x8e, 0x4f, 0x62, 0x03, 0x7b, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x43, 0x9c, 0x4d,
	0x6f, 0xed, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FindMaxClient is the client API for FindMax service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FindMaxClient interface {
	// Bi di streaming
	FindMax(ctx context.Context, opts ...grpc.CallOption) (FindMax_FindMaxClient, error)
}

type findMaxClient struct {
	cc *grpc.ClientConn
}

func NewFindMaxClient(cc *grpc.ClientConn) FindMaxClient {
	return &findMaxClient{cc}
}

func (c *findMaxClient) FindMax(ctx context.Context, opts ...grpc.CallOption) (FindMax_FindMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FindMax_serviceDesc.Streams[0], "/findmax.FindMax/FindMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &findMaxFindMaxClient{stream}
	return x, nil
}

type FindMax_FindMaxClient interface {
	Send(*FindMaxRequest) error
	Recv() (*FindMaxResponse, error)
	grpc.ClientStream
}

type findMaxFindMaxClient struct {
	grpc.ClientStream
}

func (x *findMaxFindMaxClient) Send(m *FindMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *findMaxFindMaxClient) Recv() (*FindMaxResponse, error) {
	m := new(FindMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FindMaxServer is the server API for FindMax service.
type FindMaxServer interface {
	// Bi di streaming
	FindMax(FindMax_FindMaxServer) error
}

// UnimplementedFindMaxServer can be embedded to have forward compatible implementations.
type UnimplementedFindMaxServer struct {
}

func (*UnimplementedFindMaxServer) FindMax(srv FindMax_FindMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMax not implemented")
}

func RegisterFindMaxServer(s *grpc.Server, srv FindMaxServer) {
	s.RegisterService(&_FindMax_serviceDesc, srv)
}

func _FindMax_FindMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FindMaxServer).FindMax(&findMaxFindMaxServer{stream})
}

type FindMax_FindMaxServer interface {
	Send(*FindMaxResponse) error
	Recv() (*FindMaxRequest, error)
	grpc.ServerStream
}

type findMaxFindMaxServer struct {
	grpc.ServerStream
}

func (x *findMaxFindMaxServer) Send(m *FindMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *findMaxFindMaxServer) Recv() (*FindMaxRequest, error) {
	m := new(FindMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FindMax_serviceDesc = grpc.ServiceDesc{
	ServiceName: "findmax.FindMax",
	HandlerType: (*FindMaxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindMax",
			Handler:       _FindMax_FindMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "findmax/findmax/findmax.proto",
}
